version: 2.1

jobs:
 build:
   machine:
    image: ubuntu-2204:2022.04.2
   steps:
     - checkout
     - run:
    name: Clone Main repository
    command: >-
      GIT_SSH_COMMAND='ssh -vv -i ~/.ssh/id_rsa'
      git clone git@github.com:user/pingpong-wallet.git ~/pingpong-wallet

     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: |
         echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

     # build the application image
     - run: docker build -t zengocorp/buildcontainer:$CIRCLE_BRANCH .

     # deploy the image
     - run: docker push zengocorp/buildcontainer:$CIRCLE_BRANCH
