version: 2.1

jobs:
 build:
   machine:
    image: ubuntu-2204:2022.04.2
   steps:
     - checkout
     - run:
        name: Clone Main repository
        command: >-
          git clone git@github.com:ZenGo-X/pingpong-wallet.git ./pingpong-wallet

     - run: pwd
     - run: ls -latr      

     # # start proprietary DB using private Docker image
     # # with credentials stored in the UI
     # - run: |
     #     echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

     - run: printenv

     # build the application image
     - run: docker build --build-arg ARTIFACTORY_TOKEN=$ARTIFACTORY_TOKEN -t zengocorp/buildcontainer:$CIRCLE_BRANCH .

     # deploy the image
     - run: docker push zengocorp/buildcontainer:$CIRCLE_BRANCH
